### ISSUE TITLE
Rolling debt feature

### ISSUE THREAD

**Issue by pmolina** [exactly/app#1042]
You will only be able to do this only if you have borrows, so it's going to be available on the dashboard. It should be a button (for floating and fixed) that should be something like "migrate", "move", "postpone", and then you will open a modal where you can move from floating to any active fixed pool. If can't move to the same pool you're currently having a borrow position.

Related to #962 and https://github.com/exactly/protocol/issues/596

- [x] #1068
- [x] #1069
- [x] #1070
- [x] #1071
- [x] #1072
- [x] #1073
- [ ] #1074

**Comment by pmolina** [comment]
The issue needs to be broken down. @franm91 all yours.

**Comment by FedeNZ** [comment]
[Figma link](https://www.figma.com/file/X3jYbpOqV0VsKps8B4H2Gh/01---Improvements?type=design&node-id=169-13837&t=gX50L64ePJBxRxhr-11)

**Comment by JuampiRombola** [comment]
- [ ] Implement pool selector 
- [ ] Implement position selector
- [ ] Implement slider
- [ ] Implement overview
- [ ] Integrate components in modal
- [ ] Integrate UI with contract
- [ ] Add button to open debt manager in dashboard
