### ISSUE TITLE
Implement Dashboard summary

### ISSUE THREAD

**Issue by pmolina** [exactly/app#1062]
TBD.

**Comment by FedeNZ** [comment]
Figma:
- [Desktop](https://www.figma.com/file/X3jYbpOqV0VsKps8B4H2Gh/01---Improvements?type=design&node-id=283-21714&t=gX50L64ePJBxRxhr-11)
- [Mobile](https://www.figma.com/file/X3jYbpOqV0VsKps8B4H2Gh/01---Improvements?type=design&node-id=283-22605&t=gX50L64ePJBxRxhr-11)

**Comment by JuampiRombola** [comment]
What is missing:

- [ ] Implement UI for empty states (designs are ready)
- [ ] Integrate with the previewer (useDashboard hook)



![Image](https://github.com/exactly/app/assets/11811232/0887527e-43af-4861-bd29-ea116fed6da3)
