### ISSUE TITLE
Staking page

### ISSUE THREAD

**Issue by pmolina** [exactly/app#1097]

**Comment by FedeNZ** [comment]
[Figma](https://www.figma.com/file/X3jYbpOqV0VsKps8B4H2Gh/02-|-Improvements?type=design&node-id=4168-7594&mode=design&t=FKp0crpT2BXQaD8H-11)



![Image](https://github.com/exactly/app/assets/90633141/07f6d7c0-9593-49c7-8beb-c444e65b6c2d)



![Image](https://github.com/exactly/app/assets/90633141/5d3b9046-7197-4010-889c-5258adef3a15)

**Comment by cruzdanilo** [comment]
- permit flow
- rate
- reset
