### ISSUE TITLE
Add net APR

### ISSUE THREAD

**Issue by pmolina** [exactly/app#1098]

**Comment by FedeNZ** [comment]
We'll show the NET APR on the current dashboard as an enhancement while we keep working on the full dashboard redesign.

No wallet connected
[Desktop](https://www.figma.com/file/otT0ADU1WgVSKIdAHxv3Jw/01-%7C-Webapp?type=design&node-id=230-18303&mode=design&t=0olrEihHUw2rUb6t-11) | [Mobile](https://www.figma.com/file/otT0ADU1WgVSKIdAHxv3Jw/01-%7C-Webapp?type=design&node-id=230-18319&mode=design&t=0olrEihHUw2rUb6t-11)

Wallet connected
[Desktop](https://www.figma.com/file/otT0ADU1WgVSKIdAHxv3Jw/01-%7C-Webapp?type=design&node-id=230-18577&mode=design&t=0olrEihHUw2rUb6t-11) | [Mobile](https://www.figma.com/file/otT0ADU1WgVSKIdAHxv3Jw/01-%7C-Webapp?type=design&node-id=230-18691&mode=design&t=0olrEihHUw2rUb6t-11)
