### ISSUE TITLE
Allowance information + revoke/change input and button

### ISSUE THREAD

**Issue by jgalat** [exactly/app#1193]
Related to #1190

There should be a section in the app that shows all current allowances where the spender is one of our contracts. And provide the user a way to revoke or update those amounts.

**Comment by FedeNZ** [comment]
Figma
[Desktop](https://www.figma.com/file/X3jYbpOqV0VsKps8B4H2Gh/01---Improvements?type=design&node-id=2726-63787&mode=design&t=xqF55ITZO8uHhfZ5-11)


![Image](https://github.com/exactly/app/assets/90633141/d8a4f543-c07f-405c-b69d-20d11988f84b)

**Comment by sebipap** [comment]
- [ ] ETH router add revoke for `exaWETH`
