### ISSUE TITLE
esEXA

### ISSUE THREAD

**Issue by sebipap** [exactly/app#1213]
![Image](https://user-images.githubusercontent.com/37161571/265495667-cd87ccbc-9fa6-4ec6-99e3-db7bdfa50f88.png)

**Comment by sebipap** [comment]
- [ ] analytics
- [ ] e2e test
- [ ] security hub update
- [ ] check mobile
- [ ] check themes

**Comment by cruzdanilo** [comment]
- [ ] batch reserve calls (manual multicall?)
- [ ] allowance flows (approve, permit)
- [ ] display reserve
- [ ] cancel stream

**Comment by cruzdanilo** [comment]
- [ ] test stream transfers

**Comment by cruzdanilo** [comment]
- [ ] check if wagmi auto batch is working properly for reserve calls
- [ ] implement all ga e-commerce events
- [ ] e2e: cancel
- [ ] e2e: approve flow
- [ ] hub: add new contract and audit
- [ ] announce feature deployment internally
