### ISSUE TITLE
add security headers on vercel

### ISSUE THREAD

**Issue by cruzdanilo** [exactly/app#1236]
> There are missing security headers on your website which can lead to different forms of attacks. Add the following headers: HSTS, Content Security, X-Content, Referrer Policy, and Permissions Policy. HSTS is especially important to protect from man-in-the-middle attacks, such as protocol downgrade attacks and cookie hijacking.

**Comment by cruzdanilo** [comment]
make sure safe app is still working

**Comment by jgalat** [comment]
- [ ] HSTS
- [ ] Content Security
- [ ] X-Content
- [ ] Referrer Policy
- [ ] Permissions Policy
