### ISSUE TITLE
installments ui

### ISSUE THREAD

**Issue by cruzdanilo** [exactly/app#1346]

**Comment by FedeNZ** [comment]
[Figma](https://www.figma.com/file/X3jYbpOqV0VsKps8B4H2Gh/02-%7C-Improvements?type=design&node-id=3932-2127&mode=design&t=s19jCacNaWJhNB0I-11)

**Comment by cruzdanilo** [comment]
next steps:
- approval flow
- eth flow
- consolidated apr
- analytics
- tests
- op mainnet fork
